---
downloads: ~/Downloads/ansible/

configure_dotfiles: yes
configure_sudoers: no
configure_terminal: no
configure_osx: yes

dotfiles_repo: https://github.com/deekue/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/src/dotfiles
dotfiles_prefix: "."
dotfiles_backup_existing: true
dotfiles_files:
  - config/alacritty
  - config/gh/config.yml
  - config/skhd
  - config/yabai
  - bashrc
  - bash_aliases
  - bash_logout
  - bash_completion
  - bash_completion.d
  - profile
#  - inputrc
  - osx
    # testing SpaceVim
    #- vimrc
    #- vim
  - gitconfig
  - gitignore_global
#  - screenrc
  - SpaceVim.d
  - tmux.conf
  - nethackrc
  - lynxrc

homebrew_brewfile_dir: '~/src/dotfiles'
homebrew_installed_packages:
  - bash
  - bash-completion@2
  - coreutils
  - duti
  - git
  - github/gh/gh
  - gnu-tar
  - jq
  - koekeishiya/formulae/yabai
  - koekeishiya/formulae/skhd
  - markdown
  - npm
  - pipenv
  - python
  - wget

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alacritty
  - signal
  - slack

# See `geerlingguy.mas` role documentation for usage instructions.
mas_email: ""
mas_signin_dialog: yes
#mas_password: ""
mas_installed_apps: []

osx_script: "~/.osx"
osx_script_params: "--no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: 
  # - name: '@google/clasp'
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: # []
  - name: 'black'
  - name: 'flake8'
  - name: 'virtualenv'
  - name: 'yapf'
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: # []
  - "tasks/alacritty.yml"
  
