---
# Post-install for Alacritty
#
# tasks for downloading extras will be unneeded after this PR is live
# https://github.com/alacritty/alacritty/pull/3441
#
# TODO install completions for fish, zsh
# TODO run if version number is newer
# TODO make this a role, depend on geerlingguy.homebrew for install of # alacritty

- name: Check for packaged extras
  stat:
    path: "/Applications/Alacritty.app/Contents/Resourcs/completions"
  register: alacritty_packaged_extras

- name: Get current Alacritty version
  command: /Applications/Alacritty.app/Contents/MacOS/alacritty -V
  register: alacritty_version_cmd
  changed_when: false

- name: Set Alacritty version number fact
  set_fact:
    # alacritty_version_cmd.stdout = "alacritty 0.4.3 (c723247)"
    alacritty_version: "{{ alacritty_version_cmd.stdout|regex_replace('^alacritty ([\\d.]+) .*$', '\\1') }}"

- name: Set Alacritty release URL fact
  set_fact:
    alacritty_release_url: "https://github.com/alacritty/alacritty/releases/download/v{{ alacritty_version }}/"
  when: not alacritty_packaged_extras.stat.exists
  
- block:
  - name: Download man page from release page
    get_url:
      url: "{{ alacritty_release_url }}/alacritty.1.gz"
      dest: "/usr/local/share/man/man1/alacritty.1.gz"
      mode: 0644
      group: admin
    when:
      - not alacritty_packaged_extras.stat.exists

  - name: Install man page
    shell:
      command: "gzip -c {{ alacritty_packaged_extras.stat.path|dirname }}/alacritty.man > /usr/local/share/man/man1/alacritty.1.gz"
    when:
      - alacritty_packaged_extras.stat.exists
  become: true

- block:
  - name: Check for existing bash completion dir
    stat:
      path: "/usr/local/etc/bash_completion.d"
      get_checksum: no
      get_mime: no
    register: alacritty_bashcomp

  - name: Download Bash completion
    get_url:
      url: "{{ alacritty_release_url }}/alacritty.bash"
      dest: "{{ alacritty_bashcomp.stat.path }}/alacritty"
    when:
      - alacritty_bashcomp.stat.exists
      - not alacritty_packaged_extras.stat.exists
    become: true

  - name: Install Bash completion
    copy:
      src: "{{ alacritty_packaged_extras.stat.path }}/alacritty.bash"
      dest: "{{ alacritty_bashcomp.stat.path }}/alacritty"
      remote_src: true
    when:
      - alacritty_bashcomp.stat.exists
      - alacritty_packaged_extras.stat.exists
    become: true
  become: false

- block:
  - name: Download Terminfo file
    get_url:
      url: "{{ alacritty_release_url }}/alacritty.info"
      dest: "~/Downloads/alacritty.info"
      backup: yes
    when: 
      - not alacritty_packaged_extras.stat.exists
    register: alacritty_terminfo_dl

  - name: Compile downloaded Terminfo file
    command: "tic -sxe alacritty,alacritty-direct {{ alacritty_terminfo_dl.dest }}"
    when:
      - alacritty_terminfo_dl.changed
      - not alacritty_packaged_extras.stat.exists

  - name: Compile packaged Terminfo file
    command: "tic -sxe alacritty,alacritty-direct {{ alacritty_packaged_extras.stat.path|dirname }}/alacritty.info"
    when:
      - alacritty_packaged_extras.stat.exists

  - name: Install compiled Terminfo system-wide
    copy:
      src: "~/.terminfo/61/{{ item }}"
      dest: "/usr/share/terminfo/61/{{ item }}"
      owner: "root"
      group: "wheel"
      mode: 0644
    loop:
      - "alacritty"
      - "alacritty-direct"
    when: false # TODO make this a config option in the role
    become: true
  become: false
