---
# TODO: Use sudo once .osx can be run via root with no user interaction.
- name: Ensure .osx is executable.
  file:
    path: "{{ osx_script }}"
    mode: "u=rwx"

- name: Run .osx dotfiles.
  shell: "{{ osx_script }} {{ osx_script_params }}"
  changed_when: false
